name: Build and deploy Node.js app to Azure Web App - demo-app-react

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          CI: false
        run: |
          cd .
          npm install
          npm run build --if-present
     
         

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./build

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stg'
      url: 'https://demo-app-react-stg.azurewebsites.net/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demo-app-react'
          slot-name: 'stg'  # Deploying to the staging slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
          package: ./build

  deploy-prod:
    runs-on: ubuntu-latest
    needs:  deploy-to-staging
    environment:
      name: 'prod'
      url: 'https://demo-app-react.azurewebsites.net/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demo-app-react'
          slot-name: 'Production'  # Deploying to the production slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./build
