# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - demo-app-react

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          CI: false
        run: |
          cd .
        
          npm install
          npm run build --if-present
       

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: app-demo
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stg'
      url: 'https://demo-app-react-stg.azurewebsites.net'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: app-demo

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: demo-app-react
          slot-name: stg
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_11E246186F244ADCA8329B835B69E853 }}
          package: build
